Homework 5 is done
belyalex/made_2019_cpp pull request #1
Opened 2019-11-12 19:39 UTC by belyalex

2019-11-12 21:32 UTC, smirnov-vs requested changes

2019-11-12 21:32 UTC, smirnov-vs commented on 05/serializer.h
> +	Error save_value(T val) {
скопируется сюда

2019-11-12 21:32 UTC, smirnov-vs commented on 05/serializer.h
> +		Error res = save_value(val);
нет форварда

2019-11-12 21:32 UTC, smirnov-vs commented on 05/serializer.h
> +		return load_value<T&&>(val);
это делается не так, для этого есть std::forward

2019-11-12 21:32 UTC, smirnov-vs commented on 05/serializer.h
> +Error Deserializer::load_value<bool&>(bool& val)
это по сути перегрузка, специализация не нужна

2019-11-13 09:58 UTC, belyalex commented
Привет!
 
Переделал 5 дз.
https://github.com/belyalex/made_2019_cpp/pull/1
 
--
С уважением,
Алексей Белый
 
 

2019-11-13 17:51 UTC, smirnov-vs requested changes

2019-11-13 17:51 UTC, smirnov-vs commented on 05/serializer.h
> +		return process(std::forward<ArgsT&&>(args)...);
в форварде не нужно указывать тип ссылки, он сам нужен для выбора типа ссылки
все есть в лекциях, если не хочется разбираться как это все работает, использовать не нужно

2019-11-13 17:51 UTC, smirnov-vs commented on 05/serializer.h
> +		Error res = save_value(val);
ping

2019-11-13 17:51 UTC, smirnov-vs commented on 05/serializer.h
> +		return process(std::forward<ArgsT&>(args)...);
форвард на lvalue

2019-11-13 19:15 UTC, belyalex commented on 05/serializer.h
> +		return process(std::forward<ArgsT&&>(args)...);
Про std::forward только сегодня Максим рассказал. Попытаюсь ещё раз с форвардом сделать, но уже не сегодня.

2019-11-19 20:27 UTC, smirnov-vs approved these changes
привет!
все верно

2019-11-19 20:27 UTC, smirnov-vs commented on 05/serializer.h
> +		if constexpr (std::is_same<T, bool>::value || std::is_same<T, bool&>::value) {
чтобы не писать ИЛИ можно сделать std::decay_t на T, он обрежет тип по максимуму

2019-11-19 22:31 UTC, merged