Homework 7 is done
belyalex/made_2019_cpp pull request #3
Opened 2019-11-26 17:00 UTC by belyalex

2019-11-27 19:21 UTC, smirnov-vs requested changes

2019-11-27 19:21 UTC, smirnov-vs commented on 07/format.h
> +}
лучше логику раскрутки аргументов отделить от логики наполнения результата

2019-11-27 19:21 UTC, smirnov-vs commented on 07/format.h
> +std::string format(const std::string &fmt) {
реализация функции в .h ведет к ошибкам линковки

2019-11-28 10:45 UTC, smirnov-vs requested changes

2019-11-28 10:45 UTC, smirnov-vs commented on 07/format.cpp
> +std::string subst(const std::string &fmt, const std::vector<std::string> &strings) {
эта логика все еще не отделена
раскрутка параметров в итоге вызывает разбор строки

2019-11-28 10:53 UTC, belyalex commented on 07/format.cpp
> +std::string subst(const std::string &fmt, const std::vector<std::string> &strings) {
Не понимаю, что не так.
Разбор строки вызывается, когда все variadic-параметры перенесутся в vector.

2019-11-28 10:58 UTC, smirnov-vs commented on 07/format.cpp
> +std::string subst(const std::string &fmt, const std::vector<std::string> &strings) {
Да, получается раскрутка аргументов зависит от разбора строки, хотя это по сути независимые алгоритмы и можно их вызвать независимо

2019-11-28 11:09 UTC, belyalex commented on 07/format.cpp
> +std::string subst(const std::string &fmt, const std::vector<std::string> &strings) {
Т.е. надо из format сначала вызвать раскрутку параметров, а потом подстановку их в строку?

2019-11-28 14:00 UTC, belyalex commented on 07/format.cpp
> +std::string subst(const std::string &fmt, const std::vector<std::string> &strings) {
Переделал, перенёс вызов функции подстановки параметров из функции раскрутки в функцию format.

2019-12-26 15:17 UTC, smirnov-vs approved these changes
вопросов нет, я зачел

2019-12-26 15:56 UTC, merged